### ISSUE TITLE
Stuttering/Hiccups with C+ enabled in crowded area, regardless of disabling all profiles.

### ISSUE THREAD

**Issue by Fareld87** [Aether-Tools/CustomizePlus#20]
Sorry if this has been addressed already I have realised that my stuttering is caused by C+ being enabled and when running in places like Limsa with a lot of people around even though I have all profiles disabled. Game is buttersmooth again when I disable it.

It's not hard stuttering and it's not making the game unplayable but it's there nonetheless and I was wondering if there were a way to fix that or not.

**Comment by RisaDev** [comment]
Since this isn't a mass issue and the only thing that can give performance issues when no profiles are enabled is object manager I can only suggest waiting or trying to figure out what it is with your setup that can trigger those performance issues. (like keeping only C+ enabled, reinstalling dalamud from scratch, etc)

Object manager is almost completely implemented by penumbra/glamourer so if there are any performance issues with it they will be fixed when they are fixed there.

I will keep this open and update this with information about object manager changes so you can test it again at a later date.

**Comment by Fareld87** [comment]
I have reinstalled Dalamud from scratch with only C+ downloaded and enabled and the issue still occurs for some reason, so I don't think Penumbra and Glamourer have something to do with it.

However I have capped my game to 60 fps and the stuttering/hiccups were gone (I usually have 80+ fps during peak time and 120-130 off-peak time) So it may just be the plugin not liking high framerate or something related to graphic settings? Thanks for trying to help anyway.

**Comment by RisaDev** [comment]
Not really sure what to say about that. This seems like an issue unique to your game setup. Might be DLSS/FSR related if you are using those. I have not observed c+ introducing any stuttering with high fps on my pc.

![image](https://github.com/user-attachments/assets/31904b9d-b1ed-4334-a33c-f0c73f983a6e)

Glad you've been able to find a solution though.
